/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pscheduler;

import java.awt.Color;
import javax.swing.JTextArea;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;
import org.jfree.data.time.SimpleTimePeriod;

/**
 *
 * @author SAGAR
 */
public class FCFS extends javax.swing.JInternalFrame {

    /**
     * Creates new form FCFS
     */
    double awt = 0.0;
    double atat = 0.0;
    int sum=0;
    int result[] = new int[20];
    int w[] = new int[10];
    int t[] = new int[20];
    Boolean f[] = new Boolean[10];
    int x = 50 ,y = 150 ;
    TaskSeriesCollection dataset;
    
    public FCFS() {
        initComponents();
         
        
    }

    /**
     *
     * @param n
     * @param a
     * @param b
     * @return
     */
    public double calc(int n,int a[],int b[],int p[])
    {
        
        int x,k;
        x = 0;
        k = 0;
        for(int i=0;i<10;i++)
            f[i] = false;
        for(int i=0;i<n;i++)
            sum = sum + b[i];
       
         while(x<sum){
            for(int i=0;i<n;i++)
            {
                if(a[i]<=x && f[i]==false)
                {
                    w[i] = x;
                    result[k++] = i;
                    x = x + b[i];
                    f[i] = true;
                    w[i] -=a[i];
                }
            }
        }
        for(int i=0;i<n;i++)
        {
            awt = awt + w[i];
            t[i] = w[i] + b[i];
            atat = atat + t[i];
        }
        awt = awt/n;
        atat = atat/n;
              
        JTextArea jt = new JTextArea("Process\t Arrival \t Burst\t Priority\t Wait\t TurnAround");
        for(int i=0;i<n;i++)
        {
            jt.setText(jt.getText() + "\n"+i + "\t" + a[i]+"\t"+b[i]+"\t"+p[i]+"\t"+w[i]+"\t"+t[i]);
            
        }
        jt.setText(jt.getText() + "\n\n"+"The Average Waiting Time is "+awt);
        jt.setText(jt.getText() + "\n\n"+"The Average Turn Around Time is "+atat);
        jt.setBounds(20, 100, 530, 150);
        jt.setEnabled(false);
        jDesktopPane1.add(jt, javax.swing.JLayeredPane.DEFAULT_LAYER);
         return awt;
    }
        
    public void draw(int n,int a[],int b[],int p[])
    {
               
        dataset = new TaskSeriesCollection();
        TaskSeries s1 = new TaskSeries("Planned Tasks");
        int temp=0;
        for(int k=0;k<n;k++)
        {
        s1.add(new Task("p"+result[k],new SimpleTimePeriod(temp, temp+b[result[k]])));
        temp+=b[result[k]];
        }      
        dataset.add(s1);
        JFreeChart chart =  ChartFactory.createGanttChart("Time Chart", "Processes", "Avg Waiting Time", dataset);
        CategoryPlot p1 = chart.getCategoryPlot();
        p1.setRangeGridlinePaint(Color.MAGENTA);
        ChartFrame frame = new ChartFrame("Process", chart);
        frame.setVisible(true);
        frame.setSize(600, 600);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FCFS");
        jLabel1.setBounds(160, 20, 270, 30);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
