/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pscheduler;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author SAGAR
 */
public class Main extends javax.swing.JFrame {

    int n;
    Boolean flag = false;
    JTextField j[] = new JTextField[20];
    JTextField j1[] = new JTextField[20];
    JTextField j2[] = new JTextField[20];
    int a[] = new int[30];
    int b[] = new int[30];
    int p[] = new int[30];
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();        
    int x = 300;
    int y = 150;
    int x1 = 100;
    int y1 = 150;
    double  d1,d2,d3,d4;
    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        Dimension dim = (Toolkit.getDefaultToolkit()).getScreenSize();  
        setSize(dim);
        create();
    }

    private void create()
    {       
        jLabel1.setLocation(450, 50);
        jTextField1.setLocation(600, 50);
        jButton1.setLocation(800, 50);
    }
    private void gen(int n)
    {
        
        JLabel l1 = new JLabel("Processes");
        JLabel l2 = new JLabel("Arrival Time");
        JLabel l3 = new JLabel("Burst Time");
        JLabel l4 = new JLabel("Priority");
        l1.setBounds(120, 60, 125,150);
        l2.setBounds(320, 60, 125,150);
        l3.setBounds(520, 60, 125,150);
        l4.setBounds(720, 60, 125,150);
        jDesktopPane1.add(l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.add(l2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.add(l3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.add(l4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JLabel p[] = new JLabel[20];
        for(int i=0;i<n;i++)
        {
            p[i] = new JLabel("P"+i);
            p[i].setBounds(x1, y1, 100, 50);
            jDesktopPane1.add(p[i], javax.swing.JLayeredPane.DEFAULT_LAYER);
            y1+=60;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Number of processes");
        jLabel1.setBounds(140, 30, 160, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(300, 30, 170, 40);
        jDesktopPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(480, 30, 70, 40);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        n = Integer.parseInt(jTextField1.getText());
        
        gen(n);
        for(int i=0;i<n;i++)
        {
            j[i] = new JTextField();
            j1[i] = new JTextField();
            j2[i] = new JTextField();
            j[i].setBounds(x, y, 100, 50);
            j1[i].setBounds(x+210, y, 100, 50);
            j2[i].setBounds(x+420, y, 100, 50);
            y+=60;
            jDesktopPane1.add(j[i], javax.swing.JLayeredPane.DEFAULT_LAYER);
            jDesktopPane1.add(j1[i], javax.swing.JLayeredPane.DEFAULT_LAYER);
            jDesktopPane1.add(j2[i], javax.swing.JLayeredPane.DEFAULT_LAYER);
        }
        JButton b1 = new JButton();
        b1.setBounds(x-50, y, 200, 50);
        b1.setText("Analyse");
        jDesktopPane1.add(b1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
       jButton1.setEnabled(false);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB0ActionPerformed(ActionEvent evt) {
                //To change body of generated methods, choose Tools | Templates.
        FCFS f = new FCFS();
        f.setSize(600, 400);
        jDesktopPane1.add(f);
        f.calc(n, a, b, p);
        f.draw(n, a, b, p);
        f.moveToFront();
        f.setVisible(true);
            }
   
    private void jB11ActionPerformed(ActionEvent evt) {
                 //To change body of generated methods, choose Tools | Templates.
        SJF f = new SJF();
        f.setSize(600, 400);
        jDesktopPane1.add(f);
        f.calc(n, a, b, p);
        f.draw(n, a, b, p);
        f.moveToFront();
        f.setVisible(true);
            }
    private void jB2ActionPerformed(ActionEvent evt) {
                //To change body of generated methods, choose Tools | Templates.
        Priori f = new Priori();
        f.setSize(600, 400);
        jDesktopPane1.add(f);
        f.calc(n, a, b, p);
        f.draw(n, a, b, p);
        f.moveToFront();
        f.setVisible(true);
            }
    private void jB3ActionPerformed(ActionEvent evt) {
              //To change body of generated methods, choose Tools | Templates.
        
        RR f = new RR();
        f.setSize(600, 400);
        jDesktopPane1.add(f);
        f.calc(n, a, b, p);
        f.draw(n, a, b, p);
        f.moveToFront();
        f.setVisible(true);
            }
    private void jB1ActionPerformed(java.awt.event.ActionEvent evt){
        
        try
        {
            for(int i=0;i<n;i++)
            {
                a[i] = Integer.parseInt(j[i].getText());
                b[i] = Integer.parseInt(j1[i].getText());
                p[i] = Integer.parseInt(j2[i].getText());
            }
            FCFS f = new FCFS();
            RR r = new RR();
            Priori p1 = new Priori();
            SJF s = new SJF();
            d1 = f.calc(n, a, b, p);
            d2 = r.calc(n, a, b, p);
            d3 = p1.calc(n, a, b, p);
            d4 = s.calc(n, a, b, p);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(!flag)
        {
        JButton b[] = new JButton[10];
        for(int i = 0;i<4;i++)
        {
            b[i] = new JButton();
            b[i].setBounds(x, y+100, 100, 50);
            jDesktopPane1.add(b[i], javax.swing.JLayeredPane.DEFAULT_LAYER);
           x+=110;
        }
        b[0].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }           
        });
        b[1].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB11ActionPerformed(evt);
            }

            
        });
        b[2].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }

            
        });
        b[3].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }

            
        });
        b[0].setText("FCFS");
        b[1].setText("SJF");
        b[2].setText("PRIORITY");
        b[3].setText("RR");
        flag = true;
        }
        
        dataset.setValue(d1, "time", "FCFS");
        dataset.setValue(d2, "time", "RR");
        dataset.setValue(d3, "time", "PRIORITY");
        dataset.setValue(d4, "time", "SJF");
        
        JFreeChart chart =  ChartFactory.createBarChart3D("Time Chart", "Processes", "Avg Waiting Time", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.MAGENTA);
        ChartFrame frame = new ChartFrame("Process", chart);
        frame.setVisible(true);
        frame.setSize(600, 600);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
