/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pscheduler;

import java.awt.Color;
import javax.swing.JTextArea;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;
import org.jfree.data.time.SimpleTimePeriod;

/**
 *
 * @author SAGAR
 */
public class RR extends javax.swing.JInternalFrame {

    /**
     * Creates new form RR
     */
    double rawt = 0.0;
    double ratat = 0.0;
    int tq=1,t,i,count=0,rtwt=0,rttat=0,temp,sq=0;
    int result[] = new int[30];
    TaskSeriesCollection dataset;
    class process {
	int name;
	int at;
	int burst;
	int wait;
	int tat;
	int remaining;
	};
   process p1[] = new process[20];
    public RR() {
        initComponents();
    }
    public double calc(int n,int a[],int b[],int p[]){
        int g=0;
         for(i=0;i<n;i++)
         {
            p1[i] = new process();
            p1[i].burst = b[i];
            p1[i].remaining = p1[i].burst;
            p1[i].at = 0;
         }
        t=0;
        while(true)
	{
		for(i=0,count=0;i<n;i++)
		{
			temp = tq;
			if(p1[i].remaining==0)
			{
				count++;
				continue;
			}
			if(p1[i].remaining>tq)
			{
				p1[i].remaining -= tq;
				result[g++] = i;
				t+=tq;
				
			}
			else if(p1[i].remaining>0)
			{
				temp = p1[i].remaining;
				result[g++] = i;
				t+= p1[i].remaining;
				p1[i].remaining = 0;
				
			}
			sq+=temp;
			p1[i].tat = sq;
		}
		if(n==count)
			break;
		
		rtwt = 0;
		rttat = 0;
		for(i=0;i<n;i++)
		{
			p1[i].wait = p1[i].tat - p1[i].burst;
			rtwt += p1[i].wait;
			rttat += p1[i].tat;
		}
	}
		
		rawt = (float) rtwt / n;
		ratat = (float) rttat/n;
	JTextArea jt = new JTextArea("Process\t Arrival \t Burst\t Priority\t Wait\t TurnAround");
        for(i=0;i<n;i++)
        {
            jt.setText(jt.getText() + "\n"+i + "\t" + p1[i].at+"\t"+p1[i].burst+"\t"+p[i]+"\t"+p1[i].wait+"\t"+p1[i].tat);
            
        }
        jt.setText(jt.getText() + "\n\n"+"The Average Waiting Time is "+rawt);
        jt.setText(jt.getText() + "\n\n"+"The Average Turn Around Time is "+ratat);
        jt.setBounds(20, 100, 530, 150);
        jt.setEnabled(false);
        jDesktopPane1.add(jt, javax.swing.JLayeredPane.DEFAULT_LAYER);	
		

        
        return rawt;
        
    }
    
    public void draw(int n,int a[],int b[],int p[])
    {
               
        dataset = new TaskSeriesCollection();
        TaskSeries s[] = new TaskSeries[50];
        TaskSeries s1 = new TaskSeries("Planned Tasks");
        int temp=0;
        int tbt=0;
        int y[] = new int[30];
        for(int z = 0;z<n;z++)
            tbt+=b[z];
        for(int z = 0 ; z< 10 ; z++)
            y[z] = 1;
        for(int k=0;k<tbt;k++)
        {   
            
                s[k] = new TaskSeries("p"+result[k]+"("+y[result[k]] +")");
                s[k].add(new Task("p"+result[k]+"("+y[result[k]] +")",new SimpleTimePeriod(temp, temp+4)));
                temp = temp+4;
                y[result[k]]++;
          
                
        
        //temp+=b[result[k]];
        }      
        for(int k=0;k<tbt;k++)
        dataset.add(s[k]);
        JFreeChart chart =  ChartFactory.createGanttChart("Time Chart", "Processes", "Avg Waiting Time", dataset);
        CategoryPlot p1 = chart.getCategoryPlot();
        p1.setRangeGridlinePaint(Color.MAGENTA);
        ChartFrame frame = new ChartFrame("Process", chart);
        frame.setVisible(true);
        frame.setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RR");
        jLabel2.setBounds(220, 20, 150, 40);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
